{...}: {
  home.file.".claude/settings.json".text = builtins.toJSON {
    permissions = {
      allow = [
        "Read"
        "Glob"
        "Grep"
        "WebFetch"
        "WebSearch"
        "Bash(cat:*)"
        "Bash(bat:*)"
        "Bash(ls:*)"
        "Bash(tree:*)"
        "Bash(find:*)"
        "Bash(fd:*)"
        "Bash(grep:*)"
        "Bash(rg:*)"
        "Bash(head:*)"
        "Bash(tail:*)"
        "Bash(wc:*)"
        "Bash(diff:*)"
        "Bash(file:*)"
        "Bash(stat:*)"
        "Bash(which:*)"
        "Bash(type:*)"
        "Bash(env:*)"
        "Bash(echo:*)"
        "Bash(pwd:*)"
        "Bash(cd:*)"
        "Bash(uname:*)"
        "Bash(git log:*)"
        "Bash(git status:*)"
        "Bash(git diff:*)"
        "Bash(git show:*)"
        "Bash(git branch:*)"
        "Bash(git remote:*)"
        "Bash(nix eval:*)"
        "Bash(nix flake show:*)"
        "Bash(nix flake metadata:*)"
        "Bash(nix-shell:*)"
        "Bash(pactl:*)"
        "Bash(pgrep:*)"
        "Bash(ps:*)"
        "Bash(systemctl:*)"
        "Bash(journalctl:*)"
        "Bash(fprintd-list:*)"
        "Bash(noctalia-shell:*)"
        "Bash(niri msg:*)"
        "Bash(hostname:*)"
        "Bash(ip:*)"
        "Bash(ss:*)"
        "Bash(df:*)"
        "Bash(du:*)"
        "Bash(free:*)"
        "Bash(lsblk:*)"
        "Bash(lsusb:*)"
        "Bash(lspci:*)"
        "Bash(mount:*)"
        "Bash(id:*)"
        "Bash(whoami:*)"
        "Bash(groups:*)"
      ];
      deny = [
        "Bash(rm -rf /*)"
      ];
    };
  };
}
